name: Gradle Check
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  gradle-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew check jacocoTestReport --info --no-daemon --stacktrace
      - name: Upload coverage report
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}